library(lubridate)
AllData <- read.table("household_power_consumption.txt", header = TRUE , sep = ";")
Feb2007Days2 <- subset(AllData, dmy(AllData$Date) == dmy("01-02-2007") | dmy(AllData$Date) == dmy("02-02-2007"))
rm(AllData)
Feb2007Days2$Global_active_power <- as.numeric(as.character(Feb2007Days2$Global_active_power))
par(mfcol = c(1,1))
hist(Feb2007Days2$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active power (kilowatts)")
dev.copy(png, file = "plot1.png")
dev.off()